### ISSUE TITLE
Euh ça bug là

### ISSUE THREAD

**Issue by solvictor** [Noapoleon/libft#1]
à peu près ici 

juste là

**Comment by noapoleon** [comment]
non tu ments

**Comment by bac0nb0yy** [comment]
there is a bug in the hexacimal decomposition on the front-lane of the backend javascript

**Comment by noapoleon** [comment]
> there is a bug in the hexacimal decomposition on the front-lane of the backend javascript

nej din jävla lögnare min hexadecimala upplösning är perfekt
